---
- name: GPM
  hosts: all
  user: root
  tasks:
    - name: Add text block from a file
      ansible.builtin.blockinfile:
        path: /root/.ssh/authorized_keys
        block: "{{ lookup('ansible.builtin.file', 'templates/authorized_keys.j2') }}"
        state: present

    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        # cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - vim
          - tmux
          - curl
          - wget
          - screen
          - sshguard
          - borgbackup
          - secure-delete
          - unattended-upgrades
        update_cache: true

    - name: Reboot the machine
      ansible.builtin.reboot:
        msg: "Rebooting machine"
